name: SWA Deploy (no build)

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo contents (debug)
        run: |
          pwd
          ls -la

      # This makes the action deploy your repo root as-is and skip Oryx completely
      - name: Deploy to Azure Static Web Apps (no build)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: deploy
          skip_app_build: true
          app_location: "/"          # your index.html is in repo root
          output_location: "/"       # serve the same folder (no build output)






